feat: upgrade package

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -92,6 +92,11 @@ update-configure: update-configure-stamp
 	test -f Configure
 
 update-configure-stamp:
+	if [ -e regen-configure/bin ]; then \
+	    echo "regen-configure/bin is present but should have been repacked away, aborting" 1>&2; \
+	    echo '(see README.source and https://bugs.debian.org/992200)' 1>&2; \
+	    exit 1; \
+	fi
 	mv Configure Configure.orig
 	mv config_h.SH config_h.SH.orig
 	ln -s regen-configure/U
@@ -281,12 +286,14 @@ ifeq (,$(findstring nocheck,$(DEB_BUILD_OPTIONS)))
 	  $(PERL_TO_USE) $(srcdir)/debian/check-require $(srcdir)/debian/perl-base
 endif
 
+ifeq (,$(findstring nodoc,$(DEB_BUILD_OPTIONS)))
 execute_after_dh_installman-arch:
 	# put version+arch -specific manpages in libperl5.xx
 	for prefix in perl cpan; do \
 	  mv debian/libperl$(version)/usr/share/man/man1/$$prefix.1 \
 	     debian/libperl$(version)/usr/share/man/man1/$${prefix}$(version)-$(archtriplet).1; \
 	done
+endif
 
 override_dh_strip:
 	dh_strip --no-package=perl-debug --dbg-package=perl-debug
